# Generated by Django 5.1.2 on 2024-11-01 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_homepage_appointment_info_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Service title', max_length=255)),
                ('description', models.TextField(help_text='Service description')),
                ('icon_class', models.CharField(blank=True, help_text="CSS class for the icon (e.g., 'flaticon-facial-treatment')", max_length=50)),
            ],
        ),
    ]
