# Generated by Django 5.1.2 on 2024-11-01 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0026_delete_uploadedimage'),
        ('website', '0005_servicesnippet'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the staff member.', max_length=255)),
                ('position', models.CharField(help_text='Position or title of the staff member.', max_length=255)),
                ('description', models.TextField(help_text='Brief description of the staff member.')),
                ('link', models.URLField(blank=True, help_text="URL link to the staff member's profile.")),
                ('background_image', models.ForeignKey(blank=True, help_text='Background image for the staff member.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
        ),
    ]
