# Generated by Django 5.1.2 on 2024-11-01 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0026_delete_uploadedimage'),
        ('website', '0006_staffsnippet'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the work entry.', max_length=255)),
                ('link', models.URLField(blank=True, help_text='URL link to the detailed work page or image.')),
                ('image', models.ForeignKey(blank=True, help_text='Image for the work entry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
        ),
    ]
