# Generated by Django 5.1.2 on 2024-11-01 04:47

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0026_delete_uploadedimage'),
        ('website', '0007_worksnippet'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the pricing plan (e.g., Basic, Standard).', max_length=255)),
                ('price', models.CharField(help_text='Price of the plan (e.g., $24.50).', max_length=50)),
                ('frequency', models.CharField(blank=True, help_text='Frequency of the pricing (e.g., per trip).', max_length=50)),
                ('features', wagtail.fields.StreamField([('feature', 0)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {})}, help_text='List of features included in the pricing plan.')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, help_text="URL link to the partner's website.")),
                ('image', models.ForeignKey(blank=True, help_text='Image for the partner logo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
        ),
    ]
