# Generated by Django 5.1.2 on 2024-11-01 05:51

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_countersnippet'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(default='About Us', help_text='Title for the About Us section.', max_length=255)),
                ('about_text', models.TextField(help_text='Text for the About Us section.')),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter profile URL.')),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook profile URL.')),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram profile URL.')),
                ('custom_links_title', models.CharField(default='Spa Center', help_text='Title for custom links.', max_length=255)),
                ('custom_links', wagtail.fields.StreamField([('link', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Link text', 'required': True}), 1: ('wagtail.blocks.URLBlock', (), {'help_text': 'URL for the link', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('url', 1)]], {})}, help_text='List of custom links for the footer.')),
                ('address', models.CharField(help_text='Contact address.', max_length=255)),
                ('phone', models.CharField(help_text='Contact phone number.', max_length=20)),
                ('email', models.EmailField(help_text='Contact email address.', max_length=254)),
            ],
        ),
    ]
