# Generated by Django 5.1.2 on 2024-11-05 02:40

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_productindexpage_productpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpage',
            name='description_short',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
